name: "Action for go test"
on:
  pull_request

jobs:
  go-test:
    runs-on: ubuntu-latest
    services:
      dind:
          image: docker:23.0-rc-dind-rootless
          ports:
            - 2375:2375
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Test with the Go CLI
        run: go test -v ./...